Finish basic view and update task
kaitq-afterfit/task-kanri pull request #4
Opened 2020-11-20 10:19 UTC by kaitq-afterfit

2020-11-20 10:44 UTC, khanhld94 commented on app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
@kaitq-afterfit 
show, edit update chỗ này giống nhau nên chuyển sang before_action nhé

2020-11-20 10:45 UTC, khanhld94 commented on app/controllers/tasks_controller.rb
> +    @todo_tasks = Task.where(status: 1)
@kaitq-afterfit 
e nghiên cứu chuyển status sang enum nhé

2020-11-20 10:47 UTC, khanhld94 commented on app/controllers/tasks_controller.rb
>    def index
controller này không cần authenticate user à e?

2020-11-20 10:49 UTC, khanhld94 commented on app/controllers/tasks_controller.rb
> +  def update
@kaitq-afterfit 
có edit với update mà ko có new với create à?  🤔 hay là chưa thêm

2020-11-24 09:33 UTC, kaitq-afterfit commented on app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
vâng ạ

2020-11-24 09:33 UTC, kaitq-afterfit commented on app/controllers/tasks_controller.rb
> +    @todo_tasks = Task.where(status: 1)
oke a

2020-11-24 09:33 UTC, kaitq-afterfit commented on app/controllers/tasks_controller.rb
>    def index
em authenticate ở commit sau ạ

2020-11-24 09:34 UTC, kaitq-afterfit commented on app/controllers/tasks_controller.rb
> +  def update
commit này chỉ có view và edit task nên add task em thêm ở commit sau ạ

2020-11-24 09:40 UTC, khanhld94 commented on config/routes.rb
> +  get 'labels/index'
@kaitq-afterfit 
削除お願いします。

2020-11-24 09:51 UTC, khanhld94 requested changes

2020-11-24 09:51 UTC, khanhld94 commented on app/controllers/tasks_controller.rb
> +    Task.find(params[:id]).destroy
@kaitq-afterfit 
trong trường hợp delete lỗi thì sao e?

2020-11-24 09:51 UTC, khanhld94 commented on app/controllers/labels_controller.rb
> +    @label = Label.find(params[:id])
before_action

2020-11-24 09:51 UTC, khanhld94 commented on app/controllers/labels_controller.rb
> +    Label.find(params[:id]).destroy
@kaitq-afterfit 
tương tự với task

2020-11-24 09:51 UTC, khanhld94 commented on app/views/labels/index.html.erb
> +        <% @labels.each do |label| %>
chuyển bên trong cho vào _label rồi dùng collection

2020-11-24 10:32 UTC, kaitq-afterfit commented on app/controllers/tasks_controller.rb
> +    Task.find(params[:id]).destroy
e sửa ở commit sau ạ

2020-11-24 10:34 UTC, khanhld94 commented on app/controllers/labels_controller.rb
> +  def edit
```suggestion
  def edit; end
```

2020-11-24 10:39 UTC, khanhld94 approved these changes

2020-11-24 10:39 UTC, merged